config/routes.rb
SampleApp::Application.routes.draw do
	resources :users do
		member do
		  get :following, :followers
		end
	end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
	resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true

  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id", user_id: user)
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :followers, through: :reverse_relationships
  before_save { self.email.downcase! }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX},
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }

  def feed
    Micropost.from_users_followed_by(self)
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    redirect_to root_url
  end

  private
    def micropost_params
      params.require(:micropost).permit(:content)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :signed_in_user

  respond_to :html, :js

  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    respond_with @user
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    respond_with @user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :non_signed_in_user, only: [:new, :create]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find_by(id: params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the sample App!"
      redirect_to @user
    else
     render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private
    def user_params
     params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    #Before actions
    def non_signed_in_user
      redirect_to root_path if signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      @user = User.find(params[:id])
      if !current_user.admin? || @user.admin?
        redirect_to(root_path)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

# 完全なページタイトルを生成
def full_title(page_title)
	base_title = "Ruby on Rails Tutorial Sample App"
	if page_title.empty?
		base_title
	else
		"#{base_title} | #{page_title}"
	end
end

end

app/helpers/microposts_helper.rb
module MicropostsHelper

  def wrap(content)
    sanitize(raw(content.split.map { |s| wrap_long_string(s) }.join(' ')))
  end

  private
    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text : text.scan(regex).join(zero_width_space)
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# return user's gravatar
	def gravatar_for(user, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{ gravatar_id }?s=#{ options[:size] }"
		image_tag(gravatar_url, alt: user.name, class: 'gravatar')
	end
end

app/views/layouts/_footer.html.slim
footer.footer
  small
    = link_to 'Rails Tutorial', 'http://railstutorial.jp/'
    |  by Michael Hartl
  nav
    ul
      li = link_to "About", about_path
      li = link_to "Contact", contact_path
      li = link_to 'News', 'http://news.railstutorial.jp'

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "sample app", root_path, id: "logo"
      nav
        ul.nav.pull-right
          li = link_to "Home", root_path
          li = link_to "Help", help_path
          - if signed_in?
            li = link_to "Users", users_path
            li#fat-menu.dropdown
              a.dropdown-toggle[href="#" data-toggle="dropdown"]
                | Account <b class="caret"></b>
              ul.dropdown-menu
                li = link_to "Profile", current_user
                li = link_to "Settings", edit_user_path(current_user)
                li.divider
                li = link_to "Sign out", signout_path, method: "delete"
          - else
            li = link_to "Sign in", signin_path

app/views/layouts/application.html.slim
doctype html
html lang="ja"
	head
		title = full_title(yield(:title))
		meta charset="utf-8"
		= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
		= javascript_include_tag "application", "data-turbolinks-track" => true
		= csrf_meta_tags
	body
    	= render 'layouts/header'
    	.container
        - flash.each do |key, value|
          = content_tag(:div, value, class: "alert alert-#{ key }")
        = yield
        = render 'layouts/footer'
        - if Rails.env.development?
          | #{debug(params)}
					| #{debug(request.cookie_jar)}

app/views/microposts/_micropost.html.slim
li
  span.content = micropost.content
  span.timestamp Posted #{ time_ago_in_words(micropost.created_at) } ago.
  = render 'shared/delete_link', object: micropost

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/shared/_delete_link.html.slim
- if current_user?(object.user)
    = link_to "delete", object, method: :delete, data: { confirm: "You sure?" }, title: object.content

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_explanation
    .alert.alert-error
      | The form contains
      = pluralize(object.errors.count, "error")
      | .
    ul
      = object.errors.full_messages.each do |msg|
        li
          | *
          = msg

app/views/shared/_feed.html.slim
- if @feed_items.any?
  ol.microposts
    = render partial: 'shared/feed_item', collection: @feed_items
  = will_paginate @feed_items

app/views/shared/_feed_item.html.slim
li id="#{feed_item.id}"
  = link_to gravatar_for(feed_item.user), feed_item.user
  span.user
    = link_to feed_item.user.name, feed_item.user
  span.content
    = wrap(feed_item.content)
  span.timestamp
    Posted #{time_ago_in_words(feed_item.created_at)} ago.
  = render 'shared/delete_link', object: feed_item

app/views/shared/_micropost_form.html.slim
= form_for(@micropost) do |f|
  = render 'shared/error_messages', object: f.object
  .field
    = f.text_area :content, placeholder: "Compose new micropost..."
  = f.submit "Post", class: "btn btn-large btn-primary"

app/views/shared/_stats.html.slim
- @user ||= current_user
.stats
  a href=following_user_path(@user)
    strong#following.stat
      = @user.followed_users.count
    | following
  a href=followers_user_path(@user)
    strong#followers.stat
      = @user.followers.count
    | followers

app/views/shared/_user_info.html.slim
a href="user_path(current_user)"
  = gravatar_for current_user, size: 52

h1 = current_user.name
span = link_to "view my profile", current_user
span = pluralize(current_user.microposts.count, "micropost")

app/views/static_pages/_service_home.html.slim
.center.hero-unit
  h1 Sample App

  h2 This is the home page for the Ruby on Rails tutorial sample application.

  = link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary"
= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org'

app/views/static_pages/_user_home.html.slim
.row
  aside.span4
    section = render 'shared/user_info'
    section = render 'shared/stats'
    section = render 'shared/micropost_form'
  .span8
    h3 Micropost Feed
    = render 'shared/feed'

app/views/static_pages/about.html.slim
= provide(:title, 'About')
h1 About us
p
  | The Ruby on Rails Tutorial is a project to make a book and screencasts to teach web development with Ruby on Rails. This sis the sampel application for the tutorial.

app/views/static_pages/contact.html.slim
= provide(:title, 'Contact')
h1
  | Contact
p
  | Contact Ruby on Rails Tutorial about the sample app at the contact page

app/views/static_pages/help.html.slim
= provide(:title, 'Help')
h1
  | Help
p
  | Get help on the Ruby on Rails Tutorial at the Rails Tutorial page.

app/views/static_pages/home.html.slim
- if signed_in?
  = render 'static_pages/user_home'
- else
  = render 'static_pages/service_home'

app/views/users/_fields.html.slim
= render 'shared/error_messages', object: f.object

= f.label :name
= f.text_field :name

= f.label :email
= f.text_field :email

= f.label :password
= f.password_field :password

= f.label :password_confirmation, "Confirmation"
= f.password_field :password_confirmation

app/views/users/_follow.html.slim
= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f|
  = f.hidden_field :followed_id
  = f.submit "Follow", class: "btn btn-large btn-primary"

app/views/users/_follow_form.html.slim
- unless current_user?(@user)
  #follow_form
    - if current_user.following?(@user)
      = render 'unfollow'
    - else
      = render 'follow'

app/views/users/_unfollow.html.slim
= form_for(current_user.relationships.find_by(followed_id: @user.id), html: { method: :delete }, remote: true) do |f|
  = f.submit "Unfollow", class: "btn btn-large"

app/views/users/_user.html.slim
li
  = gravatar_for user, size: 52
  = link_to user.name, user
  - if current_user.admin? && !current_user?(user)
    ||
    = link_to "delete", user, method: :delete, data: { confirm: "You sure?" }

app/views/users/edit.html.slim
= provide(:title, 'Edit user')
h1 Update your profile

.row
  .span6.offset3
    = form_for(@user) do |f|
      = render 'fields', f: f
      = f.submit "Save changes", class: "btn btn-large btn-primary"

    = gravatar_for @user
    a href="http://gravatar.com/emails" target="_blank" change

app/views/users/index.html.slim
= provide(:title, 'All users')
h1 All users

= will_paginate

ul.users
  = render @users

= will_paginate

app/views/users/new.html.slim
= provide(:title, 'Sign up')
h1 Sign up

.row
  .span6.offset3
    = form_for(@user) do |f|

      = render 'fields', f: f

      = f.submit "Create my account", class: "btn btn-large btn-primary"

app/views/users/show.html.slim
= provide(:title, @user.name)
.row
  aside.span4
    section
      h1
        = gravatar_for @user
        = @user.name
    section = render 'shared/stats'
  .span8
    = render 'follow_form' if signed_in?
    - if @user.microposts.any?
      h3 Microposts (#{@user.microposts.count})
      ol.microposts
        = render @microposts
      = will_paginate @microposts

app/views/users/show_follow.html.slim
= provide(:title, @title)
#row
  aside.span4
    section
      = gravatar_for @user
      h1 = @user.name
      span = link_to "view my profile", @user
      span
        b Microposts: = @user.microposts.count
    section
      = render 'shared/stats'
      - if @users.any?
        .user_avatars
          - @users.each do |user|
            = link_to gravatar_for(user, size: 30), user
  .span8
    h3 = @title
    - if @users.any?
      ul.users = render @users
      = will_paginate